name: Power BI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Requests
      run: pip install requests

    - name: Upload PBIX to Power BI
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}

      run: |
        python <<EOF
        import requests
        import os

        tenant_id = os.environ["TENANT_ID"]
        client_id = os.environ["CLIENT_ID"]
        client_secret = os.environ["CLIENT_SECRET"]
        workspace_id = os.environ["WORKSPACE_ID"]

        # STEP 1: GET TOKEN
        url = f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"

        data = {
            "grant_type": "client_credentials",
            "client_id": client_id,
            "client_secret": client_secret,
            "scope": "https://analysis.windows.net/powerbi/api/.default"
        }

        token_response = requests.post(url, data=data)
        access_token = token_response.json().get("access_token")

        headers = {
            "Authorization": f"Bearer {access_token}"
        }

        # STEP 2: UPLOAD PBIX
        file_path = "Sampletwo.pbix"   # 👈 yaha file name change kar sakte ho

        upload_url = f"https://api.powerbi.com/v1.0/myorg/groups/{workspace_id}/imports?datasetDisplayName=Sampletwo&nameConflict=CreateOrOverwrite"

        with open(file_path, "rb") as f:
            files = {"file": f}
            response = requests.post(upload_url, headers=headers, files=files)

        print("Status:", response.status_code)
        print("Response:", response.text)
        EOF
